apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-controller"
spec:
  type: {{ .Values.controller.service.type }}
  ports:
    - port: {{ .Values.controller.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: controller
