apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "registry.fullname" . }}
  labels:
    {{- include "registry.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "registry.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "registry.labels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "registry.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ include "registry.image.url" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DATABASE_CLIENT
              value: "postgres"
            - name: DATABASE_HOST
              value: "{{ .Release.Name }}-postgresql"
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_USERNAME
              value: "{{ .Values.postgresql.auth.username }}"
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ .Release.Name }}-postgresql"
                  key: postgres-password
            - name: DATABASE_NAME
              value: "{{ .Values.postgresql.auth.database }}"
            - name: DATABASE_SSL
              value: "false"
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
